---

name: CI

on:
  pull_request:
  push:
    branches: [main]
    paths-ignore:
    - '**.md'
    - '**.org'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        emacs_version:
          - 25.1
          - 25.2
          - 25.3
          - 26.1
          - 26.2
          - 26.3
          - 27.1
          - 27.2
          - 28.1
          - 28.2
          - 29.1
          - 29.2
          - 29.3
          - snapshot
        include:
          - os: macos-latest
            emacs_version: 29.3
    steps:
    - uses: purcell/setup-emacs@master
      with:
        version: ${{ matrix.emacs_version }}

    - uses: actions/setup-go@v5

    - uses: actions/checkout@v4

    - name: Install git-validation
      run: go install github.com/vbatts/git-validation@latest

    - name: make ci
      run: make ci
